### ISSUE TITLE
Display in main Bolt Dashboard

### ISSUE THREAD

**Issue by simplecreatif** [AppoloDev/bolt-seo#19]
Everything seems to be working great on this Bolt 4 SEO install except on the main Bolt Dashboard the display is showing actual code tags:

![bolt4_seo](https://user-images.githubusercontent.com/10013011/113205569-2a871400-92ba-11eb-886d-0761a3f4d073.png)

**Comment by nicohery** [comment]
Don't forget to define excerpt in content types.yaml :
`excerpt_format: '{teaser}'`
SEO tags will be replaced by the field chosen in excerpt_format.

**Comment by Fredxd** [comment]
Hi, sorry for late response.
This issue should be closed ?
Regards
